name: mapbox_search_flutter
description: This package provides some helper widgets to use with mapbox_search library.
version: 1.0.6+1
homepage: https://github.com/ketanchoyal/mapbox_search_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mapbox_search: ^3.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
